# Generated by Django 5.2.6 on 2025-12-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='active_streak',
        ),
    ]
